package com.keemo.petstore.bean;

// Generated 2015-9-1 13:23:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Breedingplan generated by hbm2java
 */
public class Breedingplan implements java.io.Serializable {

	private Integer id;
	private Parentcat parentcatByMother;
	private Cattery cattery;
	private Parentcat parentcatByFather;
	private Admin admin;
	private Date time;
	private Integer catcount;
	private Integer ordercount;
	private String fatherColor;
	private String motherColor;
	private Set planrecords = new HashSet(0);
	private Set breedingorders = new HashSet(0);

	public Breedingplan() {
	}

	public Breedingplan(Parentcat parentcatByMother, Cattery cattery,
			Parentcat parentcatByFather, Admin admin, Date time,
			Integer catcount, Integer ordercount, String fatherColor,
			String motherColor, Set planrecords, Set breedingorders) {
		this.parentcatByMother = parentcatByMother;
		this.cattery = cattery;
		this.parentcatByFather = parentcatByFather;
		this.admin = admin;
		this.time = time;
		this.catcount = catcount;
		this.ordercount = ordercount;
		this.fatherColor = fatherColor;
		this.motherColor = motherColor;
		this.planrecords = planrecords;
		this.breedingorders = breedingorders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Parentcat getParentcatByMother() {
		return this.parentcatByMother;
	}

	public void setParentcatByMother(Parentcat parentcatByMother) {
		this.parentcatByMother = parentcatByMother;
	}

	public Cattery getCattery() {
		return this.cattery;
	}

	public void setCattery(Cattery cattery) {
		this.cattery = cattery;
	}

	public Parentcat getParentcatByFather() {
		return this.parentcatByFather;
	}

	public void setParentcatByFather(Parentcat parentcatByFather) {
		this.parentcatByFather = parentcatByFather;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getCatcount() {
		return this.catcount;
	}

	public void setCatcount(Integer catcount) {
		this.catcount = catcount;
	}

	public Integer getOrdercount() {
		return this.ordercount;
	}

	public void setOrdercount(Integer ordercount) {
		this.ordercount = ordercount;
	}

	public String getFatherColor() {
		return this.fatherColor;
	}

	public void setFatherColor(String fatherColor) {
		this.fatherColor = fatherColor;
	}

	public String getMotherColor() {
		return this.motherColor;
	}

	public void setMotherColor(String motherColor) {
		this.motherColor = motherColor;
	}

	public Set getPlanrecords() {
		return this.planrecords;
	}

	public void setPlanrecords(Set planrecords) {
		this.planrecords = planrecords;
	}

	public Set getBreedingorders() {
		return this.breedingorders;
	}

	public void setBreedingorders(Set breedingorders) {
		this.breedingorders = breedingorders;
	}

}
