package com.keemo.petstore.bean;

// Generated 2015-7-22 14:51:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Breedingorder generated by hbm2java
 */
public class Breedingorder implements java.io.Serializable {

	private Integer id;
	private Breedingplan breedingplan;
	private Integer userid;
	private Date time;

	public Breedingorder() {
	}

	public Breedingorder(Breedingplan breedingplan, Integer userid, Date time) {
		this.breedingplan = breedingplan;
		this.userid = userid;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Breedingplan getBreedingplan() {
		return this.breedingplan;
	}

	public void setBreedingplan(Breedingplan breedingplan) {
		this.breedingplan = breedingplan;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
