package com.keemo.petstore.bean;

// Generated 2015-7-17 19:12:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Breedingplan generated by hbm2java
 */
public class Breedingplan implements java.io.Serializable {

	private int id;
	private Parentcat parentcatByMother;
	private Cattery cattery;
	private Parentcat parentcatByFather;
	private Admin admin;
	private Date time;
	private String video;

	public Breedingplan() {
	}

	public Breedingplan(int id) {
		this.id = id;
	}

	public Breedingplan(int id, Parentcat parentcatByMother, Cattery cattery,
			Parentcat parentcatByFather, Admin admin, Date time, String video) {
		this.id = id;
		this.parentcatByMother = parentcatByMother;
		this.cattery = cattery;
		this.parentcatByFather = parentcatByFather;
		this.admin = admin;
		this.time = time;
		this.video = video;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Parentcat getParentcatByMother() {
		return this.parentcatByMother;
	}

	public void setParentcatByMother(Parentcat parentcatByMother) {
		this.parentcatByMother = parentcatByMother;
	}

	public Cattery getCattery() {
		return this.cattery;
	}

	public void setCattery(Cattery cattery) {
		this.cattery = cattery;
	}

	public Parentcat getParentcatByFather() {
		return this.parentcatByFather;
	}

	public void setParentcatByFather(Parentcat parentcatByFather) {
		this.parentcatByFather = parentcatByFather;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

}
