package com.keemo.petstore.bean;

// Generated 2015-7-8 13:33:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer id;
	private Date time;
	private Integer userid;
	private Integer petid;
	private Integer count;
	private Byte ispay;

	public Cart() {
	}

	public Cart(Date time, Integer userid, Integer petid, Integer count,
			Byte ispay) {
		this.time = time;
		this.userid = userid;
		this.petid = petid;
		this.count = count;
		this.ispay = ispay;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getPetid() {
		return this.petid;
	}

	public void setPetid(Integer petid) {
		this.petid = petid;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Byte getIspay() {
		return this.ispay;
	}

	public void setIspay(Byte ispay) {
		this.ispay = ispay;
	}

}
