package com.keemo.petstore.bean;

// Generated 2015-7-10 14:31:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cat generated by hbm2java
 */
public class Cat implements java.io.Serializable {

	private Integer id;
	private Cattery cattery;
	private Catype catype;
	private Rank rank;
	private String name;
	private Boolean sex;
	private Byte pedigreeCertificate;
	private Byte immune;
	private Date birthday;
	private Integer price;
	private Integer oldprice;
	private String image;
	private Set orders = new HashSet(0);
	private Set carts = new HashSet(0);

	public Cat() {
	}

	public Cat(Cattery cattery, Catype catype, Rank rank, String name,
			Boolean sex, Byte pedigreeCertificate, Byte immune, Date birthday,
			Integer price, Integer oldprice, String image, Set orders, Set carts) {
		this.cattery = cattery;
		this.catype = catype;
		this.rank = rank;
		this.name = name;
		this.sex = sex;
		this.pedigreeCertificate = pedigreeCertificate;
		this.immune = immune;
		this.birthday = birthday;
		this.price = price;
		this.oldprice = oldprice;
		this.image = image;
		this.orders = orders;
		this.carts = carts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cattery getCattery() {
		return this.cattery;
	}

	public void setCattery(Cattery cattery) {
		this.cattery = cattery;
	}

	public Catype getCatype() {
		return this.catype;
	}

	public void setCatype(Catype catype) {
		this.catype = catype;
	}

	public Rank getRank() {
		return this.rank;
	}

	public void setRank(Rank rank) {
		this.rank = rank;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	public Byte getPedigreeCertificate() {
		return this.pedigreeCertificate;
	}

	public void setPedigreeCertificate(Byte pedigreeCertificate) {
		this.pedigreeCertificate = pedigreeCertificate;
	}

	public Byte getImmune() {
		return this.immune;
	}

	public void setImmune(Byte immune) {
		this.immune = immune;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Integer getOldprice() {
		return this.oldprice;
	}

	public void setOldprice(Integer oldprice) {
		this.oldprice = oldprice;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

	public Set getCarts() {
		return this.carts;
	}

	public void setCarts(Set carts) {
		this.carts = carts;
	}

}
