package com.keemo.petstore.bean;

// Generated 2015-7-8 13:33:08 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Catype generated by hbm2java
 */
public class Catype implements java.io.Serializable {

	private Integer id;
	private String catype;
	private Set cats = new HashSet(0);

	public Catype() {
	}

	public Catype(String catype, Set cats) {
		this.catype = catype;
		this.cats = cats;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCatype() {
		return this.catype;
	}

	public void setCatype(String catype) {
		this.catype = catype;
	}

	public Set getCats() {
		return this.cats;
	}

	public void setCats(Set cats) {
		this.cats = cats;
	}

}
