package com.keemo.petstore.bean;

// Generated 2015-7-13 13:41:38 by Hibernate Tools 3.4.0.CR1

/**
 * Follow generated by hbm2java
 */
public class Follow implements java.io.Serializable {

	private FollowId id;

	public Follow() {
	}

	public Follow(FollowId id) {
		this.id = id;
	}

	public FollowId getId() {
		return this.id;
	}

	public void setId(FollowId id) {
		this.id = id;
	}

}
