package com.keemo.petstore.bean;

// Generated 2015-7-31 20:39:05 by Hibernate Tools 3.4.0.CR1

/**
 * Imagmsg generated by hbm2java
 */
public class Imagmsg implements java.io.Serializable {

	private Integer id;
	private Cat cat;
	private String path;
	private Integer imagetype;

	public Imagmsg() {
	}

	public Imagmsg(Cat cat, String path, Integer imagetype) {
		this.cat = cat;
		this.path = path;
		this.imagetype = imagetype;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cat getCat() {
		return this.cat;
	}

	public void setCat(Cat cat) {
		this.cat = cat;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Integer getImagetype() {
		return this.imagetype;
	}

	public void setImagetype(Integer imagetype) {
		this.imagetype = imagetype;
	}

}
