package com.keemo.petstore.bean;

// Generated 2015-9-1 13:23:31 by Hibernate Tools 3.4.0.CR1

/**
 * Imagmsg generated by hbm2java
 */
public class Imagmsg implements java.io.Serializable {

	private Integer id;
	private String path;
	private Integer imagetype;
	private Integer catid;
	private Integer pid;

	public Imagmsg() {
	}

	public Imagmsg(String path, Integer imagetype, Integer catid, Integer pid) {
		this.path = path;
		this.imagetype = imagetype;
		this.catid = catid;
		this.pid = pid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Integer getImagetype() {
		return this.imagetype;
	}

	public void setImagetype(Integer imagetype) {
		this.imagetype = imagetype;
	}

	public Integer getCatid() {
		return this.catid;
	}

	public void setCatid(Integer catid) {
		this.catid = catid;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

}
