package com.keemo.petstore.bean;

// Generated 2015-7-25 14:00:42 by Hibernate Tools 3.4.0.CR1

/**
 * Imagmsg generated by hbm2java
 */
public class Imagmsg implements java.io.Serializable {

	private Integer id;
	private Cattery cattery;
	private String path;
	private Integer imagetype;

	public Imagmsg() {
	}

	public Imagmsg(Cattery cattery, String path, Integer imagetype) {
		this.cattery = cattery;
		this.path = path;
		this.imagetype = imagetype;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cattery getCattery() {
		return this.cattery;
	}

	public void setCattery(Cattery cattery) {
		this.cattery = cattery;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Integer getImagetype() {
		return this.imagetype;
	}

	public void setImagetype(Integer imagetype) {
		this.imagetype = imagetype;
	}

}
