package com.keemo.petstore.bean;

// Generated 2015-7-22 14:51:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer id;
	private Cat cat;
	private Admin admin;
	private Date time;
	private Integer count;
	private Byte ispay;
	private Set cats = new HashSet(0);

	public Order() {
	}

	public Order(Cat cat, Admin admin, Date time, Integer count, Byte ispay,
			Set cats) {
		this.cat = cat;
		this.admin = admin;
		this.time = time;
		this.count = count;
		this.ispay = ispay;
		this.cats = cats;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cat getCat() {
		return this.cat;
	}

	public void setCat(Cat cat) {
		this.cat = cat;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Byte getIspay() {
		return this.ispay;
	}

	public void setIspay(Byte ispay) {
		this.ispay = ispay;
	}

	public Set getCats() {
		return this.cats;
	}

	public void setCats(Set cats) {
		this.cats = cats;
	}

}
