package com.keemo.petstore.bean;

// Generated 2015-8-21 0:39:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Parentcat generated by hbm2java
 */
public class Parentcat implements java.io.Serializable {

	private Integer id;
	private Cattery cattery;
	private Catype catype;
	private String name;
	private Byte sex;
	private String color;
	private Set breedingplansForMother = new HashSet(0);
	private Set breedingplansForFather = new HashSet(0);

	public Parentcat() {
	}

	public Parentcat(Cattery cattery, Catype catype, String name, Byte sex,
			String color, Set breedingplansForMother, Set breedingplansForFather) {
		this.cattery = cattery;
		this.catype = catype;
		this.name = name;
		this.sex = sex;
		this.color = color;
		this.breedingplansForMother = breedingplansForMother;
		this.breedingplansForFather = breedingplansForFather;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cattery getCattery() {
		return this.cattery;
	}

	public void setCattery(Cattery cattery) {
		this.cattery = cattery;
	}

	public Catype getCatype() {
		return this.catype;
	}

	public void setCatype(Catype catype) {
		this.catype = catype;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Set getBreedingplansForMother() {
		return this.breedingplansForMother;
	}

	public void setBreedingplansForMother(Set breedingplansForMother) {
		this.breedingplansForMother = breedingplansForMother;
	}

	public Set getBreedingplansForFather() {
		return this.breedingplansForFather;
	}

	public void setBreedingplansForFather(Set breedingplansForFather) {
		this.breedingplansForFather = breedingplansForFather;
	}

}
