package com.keemo.petstore.bean;

// Generated 2015-8-4 12:37:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PedigreeCertificate generated by hbm2java
 */
public class PedigreeCertificate implements java.io.Serializable {

	private int id;
	private String pedigreeCertificate;
	private Set cats = new HashSet(0);

	public PedigreeCertificate() {
	}

	public PedigreeCertificate(int id) {
		this.id = id;
	}

	public PedigreeCertificate(int id, String pedigreeCertificate, Set cats) {
		this.id = id;
		this.pedigreeCertificate = pedigreeCertificate;
		this.cats = cats;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPedigreeCertificate() {
		return this.pedigreeCertificate;
	}

	public void setPedigreeCertificate(String pedigreeCertificate) {
		this.pedigreeCertificate = pedigreeCertificate;
	}

	public Set getCats() {
		return this.cats;
	}

	public void setCats(Set cats) {
		this.cats = cats;
	}

}
