package com.keemo.petstore.bean;

// Generated 2015-9-14 23:35:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Planrecord generated by hbm2java
 */
public class Planrecord implements java.io.Serializable {

	private Integer id;
	private Breedingplan breedingplan;
	private Date time;
	private Integer week;
	private String message;

	public Planrecord() {
	}

	public Planrecord(Breedingplan breedingplan, Date time, Integer week,
			String message) {
		this.breedingplan = breedingplan;
		this.time = time;
		this.week = week;
		this.message = message;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Breedingplan getBreedingplan() {
		return this.breedingplan;
	}

	public void setBreedingplan(Breedingplan breedingplan) {
		this.breedingplan = breedingplan;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getWeek() {
		return this.week;
	}

	public void setWeek(Integer week) {
		this.week = week;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
